"""audit user fk set null

Revision ID: 783234583028
Revises: 42ec91a540ed
Create Date: 2026-09-30 18:22:15.903608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783234583028'
down_revision: Union[str, Sequence[str], None] = '42ec91a540ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(
    'audit_logs_user_id_fkey',
    'audit_logs',
    'users',
    ['user_id'],
    ['id'],
    ondelete='SET NULL'
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
    'audit_logs_user_id_fkey',
    'audit_logs',
    type_='foreignkey'
)
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
